[package]
name = "proyect_esp32"
version = "0.1.0"
edition = "2024"

[dependencies]
esp-idf-sys = { version = "0.36.0", features = ["esp32"] }  # Bindings para ESP-IDF
esp-idf-hal = "0.45.2"  # Hardware Abstraction Layer para ESP32